services:
  zarmor-api:
    build: .
    container_name: zarmor-api
    ports:
      - "8001:8000"
    restart: always
    volumes:
      - ./Z-Armor.db:/app/Z-Armor.db
      - ./Z-Armor_behavior.json:/app/Z-Armor_behavior.json
      - ./logs:/app/logs
    environment:
      TZ: Asia/Ho_Chi_Minh