"""sync_managed_tables_to_db

Revision ID: 2efbeeedf89b
Revises: 04e3361d35cd
Create Date: 2026-03-13 11:12:28.523196+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2efbeeedf89b'
down_revision: Union[str, None] = '04e3361d35cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trade_symbol', table_name='trade_history')
    op.drop_index('idx_trade_time', table_name='trade_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_trade_time', 'trade_history', ['open_time'], unique=False)
    op.create_index('idx_trade_symbol', 'trade_history', ['symbol'], unique=False)
    # ### end Alembic commands ###
