FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../../shared /app/shared
COPY . .

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

# Không expose port — consumer only
CMD ["python", "-m", "app.main"]
